#clark rules
rule clark_classify_snakemake:
    output: "cla_{monsternr}_report.csv"
    input:  "cla_{monsternr}_out.csv"
    shell:  "./clark_classifyall_snakemake.sh {output} {input}" 

rule clark_runall_snakemake:
    output: "cla_{monsternr}_out.csv"
    input:  "{monsternr}_R1.fastq"
    shell:  "./clark_runall_snakemake.sh {output} {input}"

#kraken2 rules
rule kraken2_isolateGS_snakemake:
    output: "kra_{monsternr}_report.csv"
    input:  "kra_{monsternr}_fullreport"
    shell:  "./kraken2_isolateGS_snakemake.sh {input} {output}"

rule kraken2_runall_snakemake:
    output: "kra_{monsternr}_fullreport"
    input:  "{monsternr}_R1.fastq.gz"
    shell:  "./kraken2_runall_snakemake.sh {input} {output}"

#kaiju rules
rule kaiju_runall_snakemake:
    output: "kai_{monsternr}_out"
    input: "{monsternr}_R1.fastq.gz"
    shell:  "./kaiju_runall_snakemake.sh {input} {output}"

rule kaiju_classify_snakemake:
    output: "kai_{monsternr}_genus" , "kai_{monsternr}_species"
    input:  "kai_{monsternr}_out"
    shell:  "./kaiju_classifyall_snakemake.sh {input} {output}"