#testing snakemake rulemaking

#clark rules
rule clark_classify_snakemake:
    output: "cla_{monsternr}_report.csv"
    input:  "cla_{monsternr}_out.csv"
    shell:  "./clark_classifyall_snakemake.sh {output} {input}" 

rule clark_runall_snakemake:
    output: "cla_{monsternr}_out.csv"
    input:  "{monsternr}_R1.fastq"
    shell:  "./clark_runall_snakemake.sh {output} {input}"

#kraken2 rules
rule kraken2_isolateGS_snakemake:
    output: "kra_{monsternr}_report.csv"
    input:  "kra_{monsternr}_fullreport"
    shell:  "./kraken2_isolateGS_snakemake.sh {input} {output}"

rule kraken2_runall_snakemake:
    output: "kra_{monsternr}_fullreport"
    input:  "{monsternr}_R1.fastq"
    shell:  "./kraken2_runall_snakemake.sh {input} {output}"

#kaiju rules
